name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Rethunk-Tech/gh-actions/setup-nextjs-bun@68f159b435d9b129b8baf36436079c3e76fb3222 # v1.11
      - run: bun run lint
      - run: bun run typecheck
      - run: bun run build
